### ISSUE TITLE
Select Embedding Algorithms - FastText

### ISSUE THREAD

**Issue by seraphinatarrant** [seraphinatarrant/embedding_bias#1]
1st choice - FastText
2nd choice - GloVe

Proposed choices: word2vec, glove, fasttext, transformer encoder, etc

Everyone needs to agree on one to start with (a second one as a backup if time permits is fine).

**Comment by pandyamugdha** [comment]
FastText - will work better for Russian and Spanish than other algorithms. Using subwords is not a problem for English.

GloVe - in case we don't use other languages it makes sense to use whole words then.
