### ISSUE TITLE
Pick Languages and Downstream Tasks (+ toolkits for latter)

### ISSUE THREAD

**Issue by seraphinatarrant** [seraphinatarrant/embedding_bias#2]
Rebecca - Russian + toxicology
@rimusa - Spanish + toxicology
@pandyamugdha - English + toxicology

We need to assign who is using which English + downstream task (coref, toxicity) and what toolkit they will use.
The third person needs to pick a third downstream task, or preferably a second language + one of the same downstream tasks.

**Comment by pandyamugdha** [comment]
If needed, @pandyamugdha or Rebecca can do coreference resolution.
