### ISSUE TITLE
Identify Training Data

### ISSUE THREAD

**Issue by seraphinatarrant** [seraphinatarrant/embedding_bias#3]
Wikipedia dataset for word embeddings

This should be a group decision as well for the two people who work on English, and can be decided independently for the other language. This is extremely flexible.

**Comment by pandyamugdha** [comment]
We will need to train a model for toxicology so we need to find a dataset for that.
Coreference resolution most likely has some provision for pretrained embeddings so we only need to add a layer. 

Not sure if I have got this right. Ask @seraphinatarrant
