### ISSUE TITLE
Question about Dataset Balancing

### ISSUE THREAD

**Issue by kato8966** [seraphinatarrant/embedding_bias#5]
`README.md` says
> Dataset balancing
> 
> NB: if WEAT words are changed/added, they need to be changed/added within dataset_balancing/db_debias.py and dataset_balancing/db_overbias.py

However, I cannot find the directory `dataset_balancing`.

**Comment by seraphinatarrant** [comment]
Also just corrected, they're just in db_debias.py, those instructions predated a refactor.
