### ISSUE TITLE
Question about training data

### ISSUE THREAD

**Issue by kato8966** [seraphinatarrant/embedding_bias#6]
The paper says "To train embeddings, we use domain-matched data for each downstream task. For coreference we train on Wikipedia data, ..." in section 4.1 Datasets.
However, README.md says,

> ## Data
> ### English Coreference:
> We pretrain embeddings on the [English gigaword corpus](https://catalog.ldc.upenn.edu/LDC2003T05).

Which is right?

**Comment by seraphinatarrant** [comment]
Oh sorry, the readme was out of date from our initial experiments, good catch! We use wikipedia as the paper says. I have updated and corrected the readme.
